### PR TITLE
add visited class to topic-details to allow more styling under it

### PR DESCRIPTION
**Pull request by andrewroth**

### CODE REVIEW

**Comment by angusmcleod** [comment]
@andrewroth Hey thanks for the PR. However, I'm a little unclear as to what you're trying to achieve here. Adding the ``visited`` class to the topic-details doesn't actually change the styling of the content of topic-details as there are no relevant style rules that apply to this scenario. Perhaps you could point out what specific change you want to achieve? Thanks.

**Comment by andrewroth** [comment]
We're trying to style the preview block the same as the visited topic style
(if visited).. My post in dev that you replied to explains it a bit more
with an example.  It's for a css selector that has topic-detail.visited as
a parent node then the topic-preview as a child.  We could also put visited
on the preview detail div as well.

**Comment by angusmcleod** [comment]
@andrewroth Yes, I understand. However, the excerpt is already styled as 'gray' in Discourse. [See here](https://github.com/discourse/discourse/blob/9d8db11cf3162241d9828b8fd48cce96854f8863/app/assets/stylesheets/common/base/_topic-list.scss#L69). 

Here's a side by side comparison of a the same topic that has been visited with your change and without your change. The topic title and excerpt look the same in both.

screen shot 2016-07-27 at 7 40 20 pm
screenshot at jul 27 19-36-52

Do you have some particular style result you're trying to achieve? Could you show me a screenshot of what you except it to look like? 

Sorry to be pedantic, but I want to be sure that this is necessary to apply to the plugin, or whether it should be handled in a custom style sheet.

**Comment by andrewroth** [comment]
No problem.  This is what we're seeing:  https://www.dropbox.com/s/7ljhdojfw4rgto1/Screenshot%202016-07-27%2021.29.48.png?dl=0
So we want the topic preview to be gray like the topic link.

My coworker has been adding some custom styles.  I looked at it again from the stock install/plugin, and I think you're seeing the visited color because of :visited.  But if you visit a link while logged in, open a new browser (so you get a new session), log in, then load the topics index, I think you'll see a visited class on the title but not on the preview.

I think because of our custom styles, we want the previews to be black if not visited, and gray if visited.  By default, the styles are gray for both visited and not visited, so then it doesn't matter.

**Comment by andrewroth** [comment]
@angusmcleod Anything on this?  Did my explanation make sense?  I think my last paragraph is most accurate, I think it's the fact that the colour is grey by default, but we want black for non-visited.  If you don't think enough other people would benefit from this, we can use my fork.

**Comment by angusmcleod** [comment]
@andrewroth Sorry, been busy.

Right, I see. It will make your custom styling simpler if I merge this.

Ok, since this doesn't affect anyone else, I'll merge.

**Pull request merged**
