### PR TITLE
Pr/7

### PR DESCRIPTION
**Pull request by angusmcleod**

### CODE REVIEW

**Comment by angusmcleod** [comment]
@pmusaraj These are my edits to your work. If you're happy with them, I'll merge.

**Comment by angusmcleod** [comment]
@pmusaraj Ah I didn't check mobile web. One sec

**Comment by angusmcleod** [comment]
@pmusaraj Ah the reason the mobile view is getting messed up is because we're skipping the header purely based on ``socialMediaStyle``. The header should always be skipped on mobile view. See: https://github.com/discourse/discourse/blob/master/app/assets/javascripts/discourse/components/topic-list.js.es6#L22

**Comment by angusmcleod** [comment]
@pmusaraj Check this branch yourself and then I'll merge.

**Review by pmusaraj — APPROVED** [review]
Works well!

**Pull request merged**
