### PR TITLE
Pr/16

### PR DESCRIPTION
**Pull request by angusmcleod**
updated settings refactor branch

### CODE REVIEW

**Comment by angusmcleod** [comment]
@pmusaraj I've move the router logic to the topic list and aliased the relevant properties in the topic list items. I've also made a few other tweaks. Check it out and let me know what you think.

**Comment by pmusaraj** [comment]
Cool. Will take a look in a bit.

**Comment by angusmcleod** [comment]
@pmusaraj btw, the reason I changed the name of the settings is that I was getting various errors because the same settings used to be booleans rather than strings. To avoid having to do a migration (which is not really possible from a plugin), it is easier to just change the setting names.

**Comment by angusmcleod** [comment]
@pmusaraj btw, the reason I changed the name of the settings is that I was getting various errors because the same settings used to be booleans rather than strings. To avoid having to do a migration (which is not really possible from a plugin), it is easier to just change the setting names.

**Comment by angusmcleod** [comment]
@pmusaraj btw, the reason I changed the name of the settings is that I was getting various errors because the same settings used to be booleans rather than strings. To avoid having to do a migration (which is not really possible from a plugin), it is easier to just change the setting names.

**Comment by pmusaraj** [comment]
@angusmcleod that's the main thing I wanted to test. So, the settings will be reset on update. 

Is there a way to notify site administrators? Because this update will disable the plugin, essentially. 

This looks good. I will leave it to you to hit merge 😄 (but thanks for adding me to project!

**Comment by pmusaraj** [comment]
Spoke too soon. Problems with layout on mobile. 
iphone se ios 10 1

**Comment by angusmcleod** [comment]
@pmusaraj Right. I think this should do it:

https://github.com/angusmcleod/discourse-topic-previews/commit/e983d721826122bc977a6d34e3e8eb579b0bb989

**Comment by angusmcleod** [comment]
@pmusaraj hm just noticed another issue. Because we're using ``indexOf`` to tell if the route name contains a setting string, mobile settings are affecting desktop settings, i.e. if you have ``latest-mobile`` for social style, but not ``latest``, the social style still gets applied to latest on desktop, because the string 'latest' appears in ``latest-mobile``. I'm changing this to an exact match comparison.

**Comment by angusmcleod** [comment]
@pmusaraj I've rounded out this approach we've developed to allow granular setting of topic list display on each category as well. By default the site wide settings only affect the non-category topic lists. Each category has its own list of topic list display choices, like the site wide settings. The site wide settings can be made the default for the categories via the setting ``topic_list_set_category_defaults``

**Pull request merged**
