### PR TITLE
Combine social and tiles

### PR DESCRIPTION
**Pull request by merefield**
This PR fully replaces social style with tiles style now that it works on mobile and desktop and will operate in one column if you restrict the available width.

### CODE REVIEW

**Comment by angusmcleod** [comment]
@merefield On first load, I'm getting an exception.

screen shot 2019-02-18 at 9 23 38 am

You'll need to add a check for tags existence before iterating through them.

```
if (Discourse.SiteSettings.topic_list_tiles_larger_featured_tiles && topic.tags.filter(function (tag) {
                return _this.get('featuredTags').indexOf(tag) > -1;
              })[0]) {
                this.classNames.push('tiles-grid-item-width2');
              }
```

However, let's just break this out into a new PR. One feature per PR is best.

**Comment by merefield** [comment]
Ok will do on both counts.

**Review by angusmcleod — CHANGES_REQUESTED** [review]
I'm getting this exception when opening the category settings modal. Check that you've updated how the custom settings are initialized
screen shot 2019-02-28 at 11 11 29 am

I'm also seeing a number of remaining "social" or "social-style" strings in the plugin. Let's clean these up.

screen shot 2019-02-28 at 11 18 21 am

**Comment by merefield** [comment]
Apologies, this is all done.

**Review by angusmcleod — APPROVED** [review]

**Pull request merged**
