### PR TITLE
PERF: reduce SQL queries by aggreating records

### PR DESCRIPTION
**Pull request by erickguan**
The PR is a huge hack for performance but it works (somehow). Loading records for individual topics takes a huge amount of time in total. It's better to load them once.

I removed `first_post_id` to `previewed_post_id`. I don't understand the logic in the serializer but I think you are limiting the field when the post is loaded. It would be better to use another custom_fields to store the post_id so they can be loaded together.

There are many post action related methods in the serializer. It might be better to check the topic status in the client side to decide whether showing the button. Pushing permission check when the user click the button would save us from pushing `can_like?` to the client.

### CODE REVIEW

**Comment by angusmcleod** [comment]
@fantasticfears Thanks for taking a shot at this. I was thinking along similar lines, but didn't know where to start.

However I'm getting this error when running this branch locally.

screen shot 2016-12-18 at 3 55 01 pm

Perhaps the ``previewed_post`` attribute is not getting assigned for existing topics [here](https://github.com/fantasticfears/discourse-topic-previews/blob/perf/plugin.rb#L28
). Did you have to drop your local DB for this to work? We need to figure out an alternate solution if that is the case as there are a number of existing users.

**Comment by fantasticfears** [comment]
Fixed! I didn't know there can be a topic without a post.

**Comment by angusmcleod** [comment]
@fantasticfears hm I'm still seeing the same issue in a different place now. Could you try checking out master, create some topics, then check out this branch and see if you get the same error? I'm not sure it's because there are topics on my local with no posts in them. I'm super busy at work right now, otherwise I'd dig into a bit more.

screenshot at dec 20 18-20-14

**Comment by fantasticfears** [comment]
No problem. I'll try to dig different scenarios.

**Comment by fantasticfears** [comment]
I've updated the pull request and it's good in my end. I've removed some SQLs which require postgresql 9.4+.

**Comment by angusmcleod** [comment]
@fantasticfears Thanks! I've now got it working on my local. Perhaps it was the postgres version, albeit I seem to be running ``9.6.1``.

screen shot 2016-12-22 at 5 20 33 pm

Merging this now.

**Pull request merged**
